server:
    servlet:
        context-path: /cloudoffice/    
        
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
    profiles:
      active: prod #current application running environment
      
---
# local develompment environment
spring:
  profiles: dev
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/cloudoffice_db?max_allowed_packet=25000
    username: root 
server:
  port: 9090
    
---
# production live environment
spring:
  profiles: prod
  datasource:
    password: root2021
    url: jdbc:mysql://voffice-db.cklyua0vjw43.ap-south-1.rds.amazonaws.com:3306/voffice?max_allowed_packet=25000
    username: root 
server:
  port: 5000  

  
---
# log configuration
logging:
  file: 'D:/Java Projects Workspace/CloudOffice_ERP_Spring-Boot/logs/myLogs.log'  
#D:/Java Projects Workspace/CloudOffice_ERP_Spring-Boot/logs



